### ISSUE TITLE
Gap between paragraphs 

### ISSUE THREAD

**Issue by justindlivingstone** [livingstoneonline/Missionary-Travels#10]
Hi Adrian,

I'm beginning to ticket remaining issues in the transcriptions. The good news is that I've found very little; mostly it's just requiring a little xml tidy up. There's one issue I've spotted a couple of times though. 

To have a look, go into the MT github where all my transcriptions are in a folder, Final MT Transcriptions. Sync github first because I just a big tidy up in there! 

The issue is that an unusual gap is appearing between paragraphs on page liv_000100_0071 (in file liv_000100_0053). I'm not sure what's causing it, but I suspect it's to do with the milestone earlier in the page.

We opened an issue back in April on a similar problem on a different page, liv_000099_0244 (in file iv_000099_0229). Initially, I thought this was to do with the marginal metamark, but I can see that there's a milestone on the previous page (0243).

Thanks in advance for your help.

**Comment by awisnicki** [comment]
Here's the text from #9 since this looks like the same thing:

JL: "Transform liv_000099_0229, and then look at 0244. The big space between paragraphs, just before the placeMark metamark and the words ‘The slow pace’ shouldn’t be there. I can’t spot the problem. This doesn’t occur elsewhere in the volume. The quick fix is to remove the paragraph break and indent using spaces."

**Comment by awisnicki** [comment]
I've fixed this. Resync and double-check. If fixed, then close this ticket.

Nigel and I hit this same issue (although it might not seem like it from immediate context) some months ago: https://github.com/livingstoneonline/LEAP-XSLT/commit/ee4ea363e6279d5cdf7fd5ae26fc7c9a20636b29

Put simply, you can't have an `<hr/>` in a `<p>` because it violates HTML rules. There was an `<hr/>` higher up in each of the top paragraphs in the two cases. So I adjust the XSLT to render the `<hr/>` in a different way based on the solution Nigel previously implemented.

**Comment by justindlivingstone** [comment]
Perfect – that's fixed. Thanks Adrian. I'll close this issue now.
