### ISSUE TITLE
hi rend right not righting

### ISSUE THREAD

**Issue by kilmunbooks** [livingstoneonline/Missionary-Travels#12]
`<hi rend="right">` is sometimes not working in contents pages. Lines 184, 202, 211, 215, 253, 255, 257, 258. 
It is not working in Illustrations, 0020, either. It does if I swap the `<hi>` for a `<p>` but can't make it work with anything else.

**Comment by awisnicki** [comment]
Can you take a look at my revised file and tell me where this is still an issue?

I've fixed pages 0017 to 0019 (please double-check). I see that it's an issue on 0020. Anywhere else?

Note that you should not be using `<hi rend="right">` but rather `<seg rend="right">`. 

In any case, let's id where the issue is first and then we'll figure out what to do.

**Comment by kilmunbooks** [comment]
Hello,
Still an issue at one point in n=0017 
 `<ab rend="center">CHAPTER IX.</ab>
	<p rend="no-indent"><hi rend="small">LINYANTI. THE CHIEF SEKELETU. CUSTOMS OF THE MAKOLOLO</hi>  <hi rend="right">178</hi></p>`
And as you note still an issue in n=0020

I tried using `<seg rend="right">` but wouldn't work at all, whereas `<hi>` worked some of the time.

**Comment by awisnicki** [comment]
This is now all fixed. I needed to redo the coding completely on the XML file (note that we use seg="right" not hi="right") then twiddle with the CSS, but it all works now. Please scan over the rest of the HTML file to see that I didn't mess up anything else.

**Comment by kilmunbooks** [comment]
It looks lovely and picked up on a few Kate errors on the way. Thank you
