### ISSUE TITLE
Spacing between main text and notes

### ISSUE THREAD

**Issue by kilmunbooks** [livingstoneonline/Missionary-Travels#14]
see example 0175 and 0176 of PDF. I think it is something to do with `<p>`

**Comment by awisnicki** [comment]
I removed one `<lb>` on 0176. See screen shots. Otherwise it looks OK to me. The lines in the `<note>` look wonky because you're trying to put single quotes at the beginning of each line (and your method doesn't work evidently), but that's another ticket!

![screen shot 2017-10-09 at 19 53 33](https://user-images.githubusercontent.com/12518623/31364617-a370e918-ad2b-11e7-96ba-3fd5da64fd2a.png)
![screen shot 2017-10-09 at 19 53 36](https://user-images.githubusercontent.com/12518623/31364619-a554d2da-ad2b-11e7-945e-15b7eaf0e3fa.png)
