### ISSUE TITLE
Single quotation marks at beginning of lines in notes

### ISSUE THREAD

**Issue by kilmunbooks** [livingstoneonline/Missionary-Travels#20]
Hello,
I am trying to mimic DL's use of single quotation marks when he is quoting someone else in notes. Is it possible to make each line only ever be the width of the page it is viewed on. 
Or should I delete the single quotation marks from the start of all lines but the first line in the two instances it occurs?
See example 
`<lb/><note xml:id="note_17" rend="small">* This singular encounter, in the words of an eye-witness, happened as follows:—
<lb/>"My South African Journal is now before me, and I have got hold of the account of the lion and buffalo affair; here it is: '<date when="1846-09-15">15th Sept. 1846</date>.  
<lb/>'Oswell and I were riding this afternoon along the banks of the Limpopo, when `

**Comment by awisnicki** [comment]
This one, honestly, is one we should write off, especially if there are only two instances. Since you're using `<lb/>`, every time there is a new `<lb/>` there will be a line break. If you don't use `<lb/>`, it will always break arbitrarily based on screen width (which is want is actually preferable), but if so then I have no idea how to go about approaching *always* having a single quotation mark at the beginning of the line, i.e., it floats at the beginning of the given line. So in this case, I do think what you propose is best: "delete the single quotation marks from the start of all lines but the first line in the two instances it occurs" *plus* remove the `<lb/>`s

**Comment by kilmunbooks** [comment]
Sorted
